#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 25
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 1
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 13
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 8

enum {
  sym_any_char = 1,
  sym__standalone_break = 2,
  sym__ = 3,
  sym_paragraph_segment = 4,
  sym_escape_sequence_prefix = 5,
  sym_heading1_prefix = 6,
  sym_heading2_prefix = 7,
  sym_heading3_prefix = 8,
  sym_heading4_prefix = 9,
  sym_heading5_prefix = 10,
  sym_heading6_prefix = 11,
  sym_quote_prefix = 12,
  sym_unordered_list_prefix = 13,
  sym_marker_prefix = 14,
  sym_paragraph_delimiter = 15,
  sym_document = 16,
  sym_paragraph = 17,
  sym_escape_sequence = 18,
  sym_heading1 = 19,
  sym_heading2 = 20,
  sym_heading3 = 21,
  sym_heading4 = 22,
  sym_heading5 = 23,
  sym_heading6 = 24,
  sym_quote = 25,
  sym_unordered_list = 26,
  sym_marker = 27,
  sym__heading = 28,
  sym__detached_modifier = 29,
  aux_sym_document_repeat1 = 30,
  aux_sym_paragraph_repeat1 = 31,
  aux_sym_heading1_repeat1 = 32,
  aux_sym_heading2_repeat1 = 33,
  aux_sym_heading3_repeat1 = 34,
  aux_sym_heading4_repeat1 = 35,
  aux_sym_heading5_repeat1 = 36,
  aux_sym_heading6_repeat1 = 37,
  aux_sym_marker_repeat1 = 38,
  anon_alias_sym__segment = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_any_char] = "any_char",
  [sym__standalone_break] = "_standalone_break",
  [sym__] = "_",
  [sym_paragraph_segment] = "paragraph_segment",
  [sym_escape_sequence_prefix] = "escape_sequence_prefix",
  [sym_heading1_prefix] = "heading1_prefix",
  [sym_heading2_prefix] = "heading2_prefix",
  [sym_heading3_prefix] = "heading3_prefix",
  [sym_heading4_prefix] = "heading4_prefix",
  [sym_heading5_prefix] = "heading5_prefix",
  [sym_heading6_prefix] = "heading6_prefix",
  [sym_quote_prefix] = "quote_prefix",
  [sym_unordered_list_prefix] = "unordered_list_prefix",
  [sym_marker_prefix] = "marker_prefix",
  [sym_paragraph_delimiter] = "paragraph_delimiter",
  [sym_document] = "document",
  [sym_paragraph] = "paragraph",
  [sym_escape_sequence] = "escape_sequence",
  [sym_heading1] = "heading1",
  [sym_heading2] = "heading2",
  [sym_heading3] = "heading3",
  [sym_heading4] = "heading4",
  [sym_heading5] = "heading5",
  [sym_heading6] = "heading6",
  [sym_quote] = "quote",
  [sym_unordered_list] = "unordered_list",
  [sym_marker] = "marker",
  [sym__heading] = "_heading",
  [sym__detached_modifier] = "_detached_modifier",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_heading1_repeat1] = "heading1_repeat1",
  [aux_sym_heading2_repeat1] = "heading2_repeat1",
  [aux_sym_heading3_repeat1] = "heading3_repeat1",
  [aux_sym_heading4_repeat1] = "heading4_repeat1",
  [aux_sym_heading5_repeat1] = "heading5_repeat1",
  [aux_sym_heading6_repeat1] = "heading6_repeat1",
  [aux_sym_marker_repeat1] = "marker_repeat1",
  [anon_alias_sym__segment] = "_segment",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_any_char] = sym_any_char,
  [sym__standalone_break] = sym__standalone_break,
  [sym__] = sym__,
  [sym_paragraph_segment] = sym_paragraph_segment,
  [sym_escape_sequence_prefix] = sym_escape_sequence_prefix,
  [sym_heading1_prefix] = sym_heading1_prefix,
  [sym_heading2_prefix] = sym_heading2_prefix,
  [sym_heading3_prefix] = sym_heading3_prefix,
  [sym_heading4_prefix] = sym_heading4_prefix,
  [sym_heading5_prefix] = sym_heading5_prefix,
  [sym_heading6_prefix] = sym_heading6_prefix,
  [sym_quote_prefix] = sym_quote_prefix,
  [sym_unordered_list_prefix] = sym_unordered_list_prefix,
  [sym_marker_prefix] = sym_marker_prefix,
  [sym_paragraph_delimiter] = sym_paragraph_delimiter,
  [sym_document] = sym_document,
  [sym_paragraph] = sym_paragraph,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_heading1] = sym_heading1,
  [sym_heading2] = sym_heading2,
  [sym_heading3] = sym_heading3,
  [sym_heading4] = sym_heading4,
  [sym_heading5] = sym_heading5,
  [sym_heading6] = sym_heading6,
  [sym_quote] = sym_quote,
  [sym_unordered_list] = sym_unordered_list,
  [sym_marker] = sym_marker,
  [sym__heading] = sym__heading,
  [sym__detached_modifier] = sym__detached_modifier,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_heading1_repeat1] = aux_sym_heading1_repeat1,
  [aux_sym_heading2_repeat1] = aux_sym_heading2_repeat1,
  [aux_sym_heading3_repeat1] = aux_sym_heading3_repeat1,
  [aux_sym_heading4_repeat1] = aux_sym_heading4_repeat1,
  [aux_sym_heading5_repeat1] = aux_sym_heading5_repeat1,
  [aux_sym_heading6_repeat1] = aux_sym_heading6_repeat1,
  [aux_sym_marker_repeat1] = aux_sym_marker_repeat1,
  [anon_alias_sym__segment] = anon_alias_sym__segment,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_any_char] = {
    .visible = true,
    .named = true,
  },
  [sym__standalone_break] = {
    .visible = false,
    .named = true,
  },
  [sym__] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading1_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading2_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading3_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading4_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading5_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading6_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_unordered_list_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_heading1] = {
    .visible = true,
    .named = true,
  },
  [sym_heading2] = {
    .visible = true,
    .named = true,
  },
  [sym_heading3] = {
    .visible = true,
    .named = true,
  },
  [sym_heading4] = {
    .visible = true,
    .named = true,
  },
  [sym_heading5] = {
    .visible = true,
    .named = true,
  },
  [sym_heading6] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_unordered_list] = {
    .visible = true,
    .named = true,
  },
  [sym_marker] = {
    .visible = true,
    .named = true,
  },
  [sym__heading] = {
    .visible = false,
    .named = true,
  },
  [sym__detached_modifier] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading1_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading2_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading3_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading4_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading5_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading6_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_marker_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym__segment] = {
    .visible = true,
    .named = false,
  },
};

enum {
  field_content = 1,
  field_name = 2,
  field_subtext = 3,
  field_title = 4,
  field_token = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_name] = "name",
  [field_subtext] = "subtext",
  [field_title] = "title",
  [field_token] = "token",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 1},
  [6] = {.index = 4, .length = 2},
  [7] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_token, 1},
  [1] =
    {field_title, 1},
  [2] =
    {field_content, 1},
  [3] =
    {field_name, 1},
  [4] =
    {field_content, 2},
    {field_title, 1},
  [6] =
    {field_name, 1},
    {field_subtext, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym__segment,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_any_char);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym__standalone_break);
      if (lookahead == '\n') ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 3},
  [36] = {.lex_state = 0, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 3},
  [38] = {.lex_state = 0, .external_lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0, .external_lex_state = 3},
  [41] = {.lex_state = 1},
};

enum {
  ts_external_token__ = 0,
  ts_external_token_paragraph_segment = 1,
  ts_external_token_escape_sequence_prefix = 2,
  ts_external_token_heading1_prefix = 3,
  ts_external_token_heading2_prefix = 4,
  ts_external_token_heading3_prefix = 5,
  ts_external_token_heading4_prefix = 6,
  ts_external_token_heading5_prefix = 7,
  ts_external_token_heading6_prefix = 8,
  ts_external_token_quote_prefix = 9,
  ts_external_token_unordered_list_prefix = 10,
  ts_external_token_marker_prefix = 11,
  ts_external_token_paragraph_delimiter = 12,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__] = sym__,
  [ts_external_token_paragraph_segment] = sym_paragraph_segment,
  [ts_external_token_escape_sequence_prefix] = sym_escape_sequence_prefix,
  [ts_external_token_heading1_prefix] = sym_heading1_prefix,
  [ts_external_token_heading2_prefix] = sym_heading2_prefix,
  [ts_external_token_heading3_prefix] = sym_heading3_prefix,
  [ts_external_token_heading4_prefix] = sym_heading4_prefix,
  [ts_external_token_heading5_prefix] = sym_heading5_prefix,
  [ts_external_token_heading6_prefix] = sym_heading6_prefix,
  [ts_external_token_quote_prefix] = sym_quote_prefix,
  [ts_external_token_unordered_list_prefix] = sym_unordered_list_prefix,
  [ts_external_token_marker_prefix] = sym_marker_prefix,
  [ts_external_token_paragraph_delimiter] = sym_paragraph_delimiter,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__] = true,
    [ts_external_token_paragraph_segment] = true,
    [ts_external_token_escape_sequence_prefix] = true,
    [ts_external_token_heading1_prefix] = true,
    [ts_external_token_heading2_prefix] = true,
    [ts_external_token_heading3_prefix] = true,
    [ts_external_token_heading4_prefix] = true,
    [ts_external_token_heading5_prefix] = true,
    [ts_external_token_heading6_prefix] = true,
    [ts_external_token_quote_prefix] = true,
    [ts_external_token_unordered_list_prefix] = true,
    [ts_external_token_marker_prefix] = true,
    [ts_external_token_paragraph_delimiter] = true,
  },
  [2] = {
    [ts_external_token_paragraph_segment] = true,
    [ts_external_token_escape_sequence_prefix] = true,
    [ts_external_token_heading1_prefix] = true,
    [ts_external_token_heading2_prefix] = true,
    [ts_external_token_heading3_prefix] = true,
    [ts_external_token_heading4_prefix] = true,
    [ts_external_token_heading5_prefix] = true,
    [ts_external_token_heading6_prefix] = true,
    [ts_external_token_quote_prefix] = true,
    [ts_external_token_unordered_list_prefix] = true,
    [ts_external_token_marker_prefix] = true,
    [ts_external_token_paragraph_delimiter] = true,
  },
  [3] = {
    [ts_external_token_paragraph_segment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__standalone_break] = ACTIONS(1),
    [sym__] = ACTIONS(1),
    [sym_paragraph_segment] = ACTIONS(1),
    [sym_escape_sequence_prefix] = ACTIONS(1),
    [sym_heading1_prefix] = ACTIONS(1),
    [sym_heading2_prefix] = ACTIONS(1),
    [sym_heading3_prefix] = ACTIONS(1),
    [sym_heading4_prefix] = ACTIONS(1),
    [sym_heading5_prefix] = ACTIONS(1),
    [sym_heading6_prefix] = ACTIONS(1),
    [sym_quote_prefix] = ACTIONS(1),
    [sym_unordered_list_prefix] = ACTIONS(1),
    [sym_marker_prefix] = ACTIONS(1),
    [sym_paragraph_delimiter] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(39),
    [sym_paragraph] = STATE(6),
    [sym_escape_sequence] = STATE(6),
    [sym_heading1] = STATE(6),
    [sym_heading2] = STATE(6),
    [sym_heading3] = STATE(6),
    [sym_heading4] = STATE(6),
    [sym_heading5] = STATE(6),
    [sym_heading6] = STATE(6),
    [sym_quote] = STATE(6),
    [sym_unordered_list] = STATE(6),
    [sym_marker] = STATE(6),
    [sym__heading] = STATE(6),
    [sym__detached_modifier] = STATE(6),
    [aux_sym_document_repeat1] = STATE(6),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [sym__standalone_break] = ACTIONS(3),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(7),
    [sym_heading1_prefix] = ACTIONS(9),
    [sym_heading2_prefix] = ACTIONS(11),
    [sym_heading3_prefix] = ACTIONS(13),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(3),
  },
  [2] = {
    [sym_paragraph] = STATE(2),
    [sym_escape_sequence] = STATE(2),
    [sym_heading1] = STATE(2),
    [sym_heading2] = STATE(2),
    [sym_heading3] = STATE(2),
    [sym_heading4] = STATE(2),
    [sym_heading5] = STATE(2),
    [sym_heading6] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unordered_list] = STATE(2),
    [sym_marker] = STATE(2),
    [sym__heading] = STATE(2),
    [sym__detached_modifier] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_marker_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym__standalone_break] = ACTIONS(29),
    [sym_paragraph_segment] = ACTIONS(32),
    [sym_escape_sequence_prefix] = ACTIONS(35),
    [sym_heading1_prefix] = ACTIONS(38),
    [sym_heading2_prefix] = ACTIONS(41),
    [sym_heading3_prefix] = ACTIONS(44),
    [sym_heading4_prefix] = ACTIONS(47),
    [sym_heading5_prefix] = ACTIONS(50),
    [sym_heading6_prefix] = ACTIONS(53),
    [sym_quote_prefix] = ACTIONS(56),
    [sym_unordered_list_prefix] = ACTIONS(59),
    [sym_marker_prefix] = ACTIONS(62),
    [sym_paragraph_delimiter] = ACTIONS(29),
  },
  [3] = {
    [sym_paragraph] = STATE(2),
    [sym_escape_sequence] = STATE(2),
    [sym_heading1] = STATE(2),
    [sym_heading2] = STATE(2),
    [sym_heading3] = STATE(2),
    [sym_heading4] = STATE(2),
    [sym_heading5] = STATE(2),
    [sym_heading6] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unordered_list] = STATE(2),
    [sym_marker] = STATE(2),
    [sym__heading] = STATE(2),
    [sym__detached_modifier] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_marker_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym__standalone_break] = ACTIONS(67),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(7),
    [sym_heading1_prefix] = ACTIONS(9),
    [sym_heading2_prefix] = ACTIONS(11),
    [sym_heading3_prefix] = ACTIONS(13),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(67),
  },
  [4] = {
    [sym_paragraph] = STATE(4),
    [sym_escape_sequence] = STATE(4),
    [sym_heading1] = STATE(4),
    [sym_heading2] = STATE(4),
    [sym_heading3] = STATE(4),
    [sym_heading4] = STATE(4),
    [sym_heading5] = STATE(4),
    [sym_heading6] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_unordered_list] = STATE(4),
    [sym_marker] = STATE(4),
    [sym__heading] = STATE(4),
    [sym__detached_modifier] = STATE(4),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym__standalone_break] = ACTIONS(71),
    [sym_paragraph_segment] = ACTIONS(74),
    [sym_escape_sequence_prefix] = ACTIONS(77),
    [sym_heading1_prefix] = ACTIONS(80),
    [sym_heading2_prefix] = ACTIONS(83),
    [sym_heading3_prefix] = ACTIONS(86),
    [sym_heading4_prefix] = ACTIONS(89),
    [sym_heading5_prefix] = ACTIONS(92),
    [sym_heading6_prefix] = ACTIONS(95),
    [sym_quote_prefix] = ACTIONS(98),
    [sym_unordered_list_prefix] = ACTIONS(101),
    [sym_marker_prefix] = ACTIONS(104),
    [sym_paragraph_delimiter] = ACTIONS(71),
  },
  [5] = {
    [sym_paragraph] = STATE(3),
    [sym_escape_sequence] = STATE(3),
    [sym_heading1] = STATE(3),
    [sym_heading2] = STATE(3),
    [sym_heading3] = STATE(3),
    [sym_heading4] = STATE(3),
    [sym_heading5] = STATE(3),
    [sym_heading6] = STATE(3),
    [sym_quote] = STATE(3),
    [sym_unordered_list] = STATE(3),
    [sym_marker] = STATE(3),
    [sym__heading] = STATE(3),
    [sym__detached_modifier] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_marker_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(107),
    [sym__standalone_break] = ACTIONS(109),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(7),
    [sym_heading1_prefix] = ACTIONS(9),
    [sym_heading2_prefix] = ACTIONS(11),
    [sym_heading3_prefix] = ACTIONS(13),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(109),
  },
  [6] = {
    [sym_paragraph] = STATE(4),
    [sym_escape_sequence] = STATE(4),
    [sym_heading1] = STATE(4),
    [sym_heading2] = STATE(4),
    [sym_heading3] = STATE(4),
    [sym_heading4] = STATE(4),
    [sym_heading5] = STATE(4),
    [sym_heading6] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_unordered_list] = STATE(4),
    [sym_marker] = STATE(4),
    [sym__heading] = STATE(4),
    [sym__detached_modifier] = STATE(4),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(111),
    [sym__standalone_break] = ACTIONS(113),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(7),
    [sym_heading1_prefix] = ACTIONS(9),
    [sym_heading2_prefix] = ACTIONS(11),
    [sym_heading3_prefix] = ACTIONS(13),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(113),
  },
  [7] = {
    [sym_paragraph] = STATE(7),
    [sym_heading2] = STATE(7),
    [sym_heading3] = STATE(7),
    [sym_heading4] = STATE(7),
    [sym_heading5] = STATE(7),
    [sym_heading6] = STATE(7),
    [sym_quote] = STATE(7),
    [sym_unordered_list] = STATE(7),
    [sym_marker] = STATE(7),
    [sym__detached_modifier] = STATE(7),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading1_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(115),
    [sym__standalone_break] = ACTIONS(117),
    [sym_paragraph_segment] = ACTIONS(120),
    [sym_escape_sequence_prefix] = ACTIONS(115),
    [sym_heading1_prefix] = ACTIONS(115),
    [sym_heading2_prefix] = ACTIONS(123),
    [sym_heading3_prefix] = ACTIONS(126),
    [sym_heading4_prefix] = ACTIONS(129),
    [sym_heading5_prefix] = ACTIONS(132),
    [sym_heading6_prefix] = ACTIONS(135),
    [sym_quote_prefix] = ACTIONS(138),
    [sym_unordered_list_prefix] = ACTIONS(141),
    [sym_marker_prefix] = ACTIONS(144),
    [sym_paragraph_delimiter] = ACTIONS(115),
  },
  [8] = {
    [sym_paragraph] = STATE(7),
    [sym_heading2] = STATE(7),
    [sym_heading3] = STATE(7),
    [sym_heading4] = STATE(7),
    [sym_heading5] = STATE(7),
    [sym_heading6] = STATE(7),
    [sym_quote] = STATE(7),
    [sym_unordered_list] = STATE(7),
    [sym_marker] = STATE(7),
    [sym__detached_modifier] = STATE(7),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading1_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(147),
    [sym__standalone_break] = ACTIONS(149),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(147),
    [sym_heading1_prefix] = ACTIONS(147),
    [sym_heading2_prefix] = ACTIONS(11),
    [sym_heading3_prefix] = ACTIONS(13),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(147),
  },
  [9] = {
    [sym_paragraph] = STATE(8),
    [sym_heading2] = STATE(8),
    [sym_heading3] = STATE(8),
    [sym_heading4] = STATE(8),
    [sym_heading5] = STATE(8),
    [sym_heading6] = STATE(8),
    [sym_quote] = STATE(8),
    [sym_unordered_list] = STATE(8),
    [sym_marker] = STATE(8),
    [sym__detached_modifier] = STATE(8),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading1_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(151),
    [sym__standalone_break] = ACTIONS(153),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(151),
    [sym_heading1_prefix] = ACTIONS(151),
    [sym_heading2_prefix] = ACTIONS(11),
    [sym_heading3_prefix] = ACTIONS(13),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(151),
  },
  [10] = {
    [sym_paragraph] = STATE(10),
    [sym_heading3] = STATE(10),
    [sym_heading4] = STATE(10),
    [sym_heading5] = STATE(10),
    [sym_heading6] = STATE(10),
    [sym_quote] = STATE(10),
    [sym_unordered_list] = STATE(10),
    [sym_marker] = STATE(10),
    [sym__detached_modifier] = STATE(10),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading2_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(155),
    [sym__standalone_break] = ACTIONS(157),
    [sym_paragraph_segment] = ACTIONS(160),
    [sym_escape_sequence_prefix] = ACTIONS(155),
    [sym_heading1_prefix] = ACTIONS(155),
    [sym_heading2_prefix] = ACTIONS(155),
    [sym_heading3_prefix] = ACTIONS(163),
    [sym_heading4_prefix] = ACTIONS(166),
    [sym_heading5_prefix] = ACTIONS(169),
    [sym_heading6_prefix] = ACTIONS(172),
    [sym_quote_prefix] = ACTIONS(175),
    [sym_unordered_list_prefix] = ACTIONS(178),
    [sym_marker_prefix] = ACTIONS(181),
    [sym_paragraph_delimiter] = ACTIONS(155),
  },
  [11] = {
    [sym_paragraph] = STATE(10),
    [sym_heading3] = STATE(10),
    [sym_heading4] = STATE(10),
    [sym_heading5] = STATE(10),
    [sym_heading6] = STATE(10),
    [sym_quote] = STATE(10),
    [sym_unordered_list] = STATE(10),
    [sym_marker] = STATE(10),
    [sym__detached_modifier] = STATE(10),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading2_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(184),
    [sym__standalone_break] = ACTIONS(186),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(184),
    [sym_heading1_prefix] = ACTIONS(184),
    [sym_heading2_prefix] = ACTIONS(184),
    [sym_heading3_prefix] = ACTIONS(13),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(184),
  },
  [12] = {
    [sym_paragraph] = STATE(11),
    [sym_heading3] = STATE(11),
    [sym_heading4] = STATE(11),
    [sym_heading5] = STATE(11),
    [sym_heading6] = STATE(11),
    [sym_quote] = STATE(11),
    [sym_unordered_list] = STATE(11),
    [sym_marker] = STATE(11),
    [sym__detached_modifier] = STATE(11),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading2_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(188),
    [sym__standalone_break] = ACTIONS(190),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(188),
    [sym_heading1_prefix] = ACTIONS(188),
    [sym_heading2_prefix] = ACTIONS(188),
    [sym_heading3_prefix] = ACTIONS(13),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(188),
  },
  [13] = {
    [sym_paragraph] = STATE(13),
    [sym_heading4] = STATE(13),
    [sym_heading5] = STATE(13),
    [sym_heading6] = STATE(13),
    [sym_quote] = STATE(13),
    [sym_unordered_list] = STATE(13),
    [sym_marker] = STATE(13),
    [sym__detached_modifier] = STATE(13),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading3_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(192),
    [sym__standalone_break] = ACTIONS(194),
    [sym_paragraph_segment] = ACTIONS(197),
    [sym_escape_sequence_prefix] = ACTIONS(192),
    [sym_heading1_prefix] = ACTIONS(192),
    [sym_heading2_prefix] = ACTIONS(192),
    [sym_heading3_prefix] = ACTIONS(192),
    [sym_heading4_prefix] = ACTIONS(200),
    [sym_heading5_prefix] = ACTIONS(203),
    [sym_heading6_prefix] = ACTIONS(206),
    [sym_quote_prefix] = ACTIONS(209),
    [sym_unordered_list_prefix] = ACTIONS(212),
    [sym_marker_prefix] = ACTIONS(215),
    [sym_paragraph_delimiter] = ACTIONS(192),
  },
  [14] = {
    [sym_paragraph] = STATE(13),
    [sym_heading4] = STATE(13),
    [sym_heading5] = STATE(13),
    [sym_heading6] = STATE(13),
    [sym_quote] = STATE(13),
    [sym_unordered_list] = STATE(13),
    [sym_marker] = STATE(13),
    [sym__detached_modifier] = STATE(13),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading3_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(218),
    [sym__standalone_break] = ACTIONS(220),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(218),
    [sym_heading1_prefix] = ACTIONS(218),
    [sym_heading2_prefix] = ACTIONS(218),
    [sym_heading3_prefix] = ACTIONS(218),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(218),
  },
  [15] = {
    [sym_paragraph] = STATE(14),
    [sym_heading4] = STATE(14),
    [sym_heading5] = STATE(14),
    [sym_heading6] = STATE(14),
    [sym_quote] = STATE(14),
    [sym_unordered_list] = STATE(14),
    [sym_marker] = STATE(14),
    [sym__detached_modifier] = STATE(14),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading3_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(222),
    [sym__standalone_break] = ACTIONS(224),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(222),
    [sym_heading1_prefix] = ACTIONS(222),
    [sym_heading2_prefix] = ACTIONS(222),
    [sym_heading3_prefix] = ACTIONS(222),
    [sym_heading4_prefix] = ACTIONS(15),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(222),
  },
  [16] = {
    [sym_paragraph] = STATE(18),
    [sym_heading5] = STATE(18),
    [sym_heading6] = STATE(18),
    [sym_quote] = STATE(18),
    [sym_unordered_list] = STATE(18),
    [sym_marker] = STATE(18),
    [sym__detached_modifier] = STATE(18),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading4_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(226),
    [sym__standalone_break] = ACTIONS(228),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(226),
    [sym_heading1_prefix] = ACTIONS(226),
    [sym_heading2_prefix] = ACTIONS(226),
    [sym_heading3_prefix] = ACTIONS(226),
    [sym_heading4_prefix] = ACTIONS(226),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(226),
  },
  [17] = {
    [sym_paragraph] = STATE(17),
    [sym_heading5] = STATE(17),
    [sym_heading6] = STATE(17),
    [sym_quote] = STATE(17),
    [sym_unordered_list] = STATE(17),
    [sym_marker] = STATE(17),
    [sym__detached_modifier] = STATE(17),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading4_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(230),
    [sym__standalone_break] = ACTIONS(232),
    [sym_paragraph_segment] = ACTIONS(235),
    [sym_escape_sequence_prefix] = ACTIONS(230),
    [sym_heading1_prefix] = ACTIONS(230),
    [sym_heading2_prefix] = ACTIONS(230),
    [sym_heading3_prefix] = ACTIONS(230),
    [sym_heading4_prefix] = ACTIONS(230),
    [sym_heading5_prefix] = ACTIONS(238),
    [sym_heading6_prefix] = ACTIONS(241),
    [sym_quote_prefix] = ACTIONS(244),
    [sym_unordered_list_prefix] = ACTIONS(247),
    [sym_marker_prefix] = ACTIONS(250),
    [sym_paragraph_delimiter] = ACTIONS(230),
  },
  [18] = {
    [sym_paragraph] = STATE(17),
    [sym_heading5] = STATE(17),
    [sym_heading6] = STATE(17),
    [sym_quote] = STATE(17),
    [sym_unordered_list] = STATE(17),
    [sym_marker] = STATE(17),
    [sym__detached_modifier] = STATE(17),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading4_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(253),
    [sym__standalone_break] = ACTIONS(255),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(253),
    [sym_heading1_prefix] = ACTIONS(253),
    [sym_heading2_prefix] = ACTIONS(253),
    [sym_heading3_prefix] = ACTIONS(253),
    [sym_heading4_prefix] = ACTIONS(253),
    [sym_heading5_prefix] = ACTIONS(17),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(253),
  },
  [19] = {
    [sym_paragraph] = STATE(21),
    [sym_heading6] = STATE(21),
    [sym_quote] = STATE(21),
    [sym_unordered_list] = STATE(21),
    [sym_marker] = STATE(21),
    [sym__detached_modifier] = STATE(21),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading5_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(257),
    [sym__standalone_break] = ACTIONS(259),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(257),
    [sym_heading1_prefix] = ACTIONS(257),
    [sym_heading2_prefix] = ACTIONS(257),
    [sym_heading3_prefix] = ACTIONS(257),
    [sym_heading4_prefix] = ACTIONS(257),
    [sym_heading5_prefix] = ACTIONS(257),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(257),
  },
  [20] = {
    [sym_paragraph] = STATE(20),
    [sym_heading6] = STATE(20),
    [sym_quote] = STATE(20),
    [sym_unordered_list] = STATE(20),
    [sym_marker] = STATE(20),
    [sym__detached_modifier] = STATE(20),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading5_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(261),
    [sym__standalone_break] = ACTIONS(263),
    [sym_paragraph_segment] = ACTIONS(266),
    [sym_escape_sequence_prefix] = ACTIONS(261),
    [sym_heading1_prefix] = ACTIONS(261),
    [sym_heading2_prefix] = ACTIONS(261),
    [sym_heading3_prefix] = ACTIONS(261),
    [sym_heading4_prefix] = ACTIONS(261),
    [sym_heading5_prefix] = ACTIONS(261),
    [sym_heading6_prefix] = ACTIONS(269),
    [sym_quote_prefix] = ACTIONS(272),
    [sym_unordered_list_prefix] = ACTIONS(275),
    [sym_marker_prefix] = ACTIONS(278),
    [sym_paragraph_delimiter] = ACTIONS(261),
  },
  [21] = {
    [sym_paragraph] = STATE(20),
    [sym_heading6] = STATE(20),
    [sym_quote] = STATE(20),
    [sym_unordered_list] = STATE(20),
    [sym_marker] = STATE(20),
    [sym__detached_modifier] = STATE(20),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading5_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(281),
    [sym__standalone_break] = ACTIONS(283),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(281),
    [sym_heading1_prefix] = ACTIONS(281),
    [sym_heading2_prefix] = ACTIONS(281),
    [sym_heading3_prefix] = ACTIONS(281),
    [sym_heading4_prefix] = ACTIONS(281),
    [sym_heading5_prefix] = ACTIONS(281),
    [sym_heading6_prefix] = ACTIONS(19),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(281),
  },
  [22] = {
    [sym_paragraph] = STATE(22),
    [sym_quote] = STATE(22),
    [sym_unordered_list] = STATE(22),
    [sym_marker] = STATE(22),
    [sym__detached_modifier] = STATE(22),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading6_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(285),
    [sym__standalone_break] = ACTIONS(287),
    [sym_paragraph_segment] = ACTIONS(290),
    [sym_escape_sequence_prefix] = ACTIONS(285),
    [sym_heading1_prefix] = ACTIONS(285),
    [sym_heading2_prefix] = ACTIONS(285),
    [sym_heading3_prefix] = ACTIONS(285),
    [sym_heading4_prefix] = ACTIONS(285),
    [sym_heading5_prefix] = ACTIONS(285),
    [sym_heading6_prefix] = ACTIONS(285),
    [sym_quote_prefix] = ACTIONS(293),
    [sym_unordered_list_prefix] = ACTIONS(296),
    [sym_marker_prefix] = ACTIONS(299),
    [sym_paragraph_delimiter] = ACTIONS(285),
  },
  [23] = {
    [sym_paragraph] = STATE(24),
    [sym_quote] = STATE(24),
    [sym_unordered_list] = STATE(24),
    [sym_marker] = STATE(24),
    [sym__detached_modifier] = STATE(24),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading6_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(302),
    [sym__standalone_break] = ACTIONS(304),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(302),
    [sym_heading1_prefix] = ACTIONS(302),
    [sym_heading2_prefix] = ACTIONS(302),
    [sym_heading3_prefix] = ACTIONS(302),
    [sym_heading4_prefix] = ACTIONS(302),
    [sym_heading5_prefix] = ACTIONS(302),
    [sym_heading6_prefix] = ACTIONS(302),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(302),
  },
  [24] = {
    [sym_paragraph] = STATE(22),
    [sym_quote] = STATE(22),
    [sym_unordered_list] = STATE(22),
    [sym_marker] = STATE(22),
    [sym__detached_modifier] = STATE(22),
    [aux_sym_paragraph_repeat1] = STATE(25),
    [aux_sym_heading6_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(306),
    [sym__standalone_break] = ACTIONS(308),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_escape_sequence_prefix] = ACTIONS(306),
    [sym_heading1_prefix] = ACTIONS(306),
    [sym_heading2_prefix] = ACTIONS(306),
    [sym_heading3_prefix] = ACTIONS(306),
    [sym_heading4_prefix] = ACTIONS(306),
    [sym_heading5_prefix] = ACTIONS(306),
    [sym_heading6_prefix] = ACTIONS(306),
    [sym_quote_prefix] = ACTIONS(21),
    [sym_unordered_list_prefix] = ACTIONS(23),
    [sym_marker_prefix] = ACTIONS(25),
    [sym_paragraph_delimiter] = ACTIONS(306),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(5), 1,
      sym_paragraph_segment,
    STATE(26), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(310), 13,
      sym_escape_sequence_prefix,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote_prefix,
      sym_unordered_list_prefix,
      sym_marker_prefix,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [22] = 3,
    ACTIONS(314), 1,
      sym_paragraph_segment,
    STATE(26), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(312), 13,
      sym_escape_sequence_prefix,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote_prefix,
      sym_unordered_list_prefix,
      sym_marker_prefix,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [44] = 1,
    ACTIONS(317), 14,
      sym_paragraph_segment,
      sym_escape_sequence_prefix,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote_prefix,
      sym_unordered_list_prefix,
      sym_marker_prefix,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [61] = 1,
    ACTIONS(319), 14,
      sym_paragraph_segment,
      sym_escape_sequence_prefix,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote_prefix,
      sym_unordered_list_prefix,
      sym_marker_prefix,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [78] = 1,
    ACTIONS(321), 14,
      sym_paragraph_segment,
      sym_escape_sequence_prefix,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote_prefix,
      sym_unordered_list_prefix,
      sym_marker_prefix,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [95] = 1,
    ACTIONS(323), 14,
      sym_paragraph_segment,
      sym_escape_sequence_prefix,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote_prefix,
      sym_unordered_list_prefix,
      sym_marker_prefix,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [112] = 3,
    ACTIONS(5), 1,
      sym_paragraph_segment,
    STATE(25), 1,
      aux_sym_paragraph_repeat1,
    STATE(29), 1,
      sym_paragraph,
  [122] = 1,
    ACTIONS(325), 1,
      sym_paragraph_segment,
  [126] = 1,
    ACTIONS(327), 1,
      sym_paragraph_segment,
  [130] = 1,
    ACTIONS(329), 1,
      sym_paragraph_segment,
  [134] = 1,
    ACTIONS(331), 1,
      sym_paragraph_segment,
  [138] = 1,
    ACTIONS(333), 1,
      sym_paragraph_segment,
  [142] = 1,
    ACTIONS(335), 1,
      sym_paragraph_segment,
  [146] = 1,
    ACTIONS(337), 1,
      sym_paragraph_segment,
  [150] = 1,
    ACTIONS(339), 1,
      ts_builtin_sym_end,
  [154] = 1,
    ACTIONS(341), 1,
      sym_paragraph_segment,
  [158] = 1,
    ACTIONS(343), 1,
      sym_any_char,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(25)] = 0,
  [SMALL_STATE(26)] = 22,
  [SMALL_STATE(27)] = 44,
  [SMALL_STATE(28)] = 61,
  [SMALL_STATE(29)] = 78,
  [SMALL_STATE(30)] = 95,
  [SMALL_STATE(31)] = 112,
  [SMALL_STATE(32)] = 122,
  [SMALL_STATE(33)] = 126,
  [SMALL_STATE(34)] = 130,
  [SMALL_STATE(35)] = 134,
  [SMALL_STATE(36)] = 138,
  [SMALL_STATE(37)] = 142,
  [SMALL_STATE(38)] = 146,
  [SMALL_STATE(39)] = 150,
  [SMALL_STATE(40)] = 154,
  [SMALL_STATE(41)] = 158,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(2),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(30),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(41),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(37),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(36),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(35),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(34),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(38),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(32),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(40),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(31),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_marker_repeat1, 2), SHIFT_REPEAT(33),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker, 3, .production_id = 7),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(30),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(41),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(37),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(36),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(35),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(34),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(38),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(32),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(40),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(31),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(33),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker, 2, .production_id = 5),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(7),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(30),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(36),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(35),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(34),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(38),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(32),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(40),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(31),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(33),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading1, 3, .production_id = 6),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading1, 2, .production_id = 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(10),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(30),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(35),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(34),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(38),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(32),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(40),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(31),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(33),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading2, 3, .production_id = 6),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading2, 2, .production_id = 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(13),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(30),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(34),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(38),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(32),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(40),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(31),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(33),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading3, 3, .production_id = 6),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading3, 2, .production_id = 3),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading4, 2, .production_id = 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(17),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(30),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(38),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(32),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(40),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(31),
  [250] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(33),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading4, 3, .production_id = 6),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading5, 2, .production_id = 3),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2), SHIFT_REPEAT(20),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2), SHIFT_REPEAT(30),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2), SHIFT_REPEAT(32),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2), SHIFT_REPEAT(40),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2), SHIFT_REPEAT(31),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2), SHIFT_REPEAT(33),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading5, 3, .production_id = 6),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading6_repeat1, 2),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading6_repeat1, 2), SHIFT_REPEAT(22),
  [290] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading6_repeat1, 2), SHIFT_REPEAT(30),
  [293] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading6_repeat1, 2), SHIFT_REPEAT(40),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading6_repeat1, 2), SHIFT_REPEAT(31),
  [299] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading6_repeat1, 2), SHIFT_REPEAT(33),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading6, 2, .production_id = 3),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading6, 3, .production_id = 6),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [314] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(30),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 2, .production_id = 2),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, .production_id = 4),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unordered_list, 2, .production_id = 4),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 1, .production_id = 1),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [339] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_norg_external_scanner_create(void);
void tree_sitter_norg_external_scanner_destroy(void *);
bool tree_sitter_norg_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_norg_external_scanner_serialize(void *, char *);
void tree_sitter_norg_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_norg(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_norg_external_scanner_create,
      tree_sitter_norg_external_scanner_destroy,
      tree_sitter_norg_external_scanner_scan,
      tree_sitter_norg_external_scanner_serialize,
      tree_sitter_norg_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
