#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 22
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 1
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 12
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 4

enum {
  sym__standalone_break = 1,
  sym__ = 2,
  sym_paragraph_segment = 3,
  sym__hard_line_break = 4,
  sym_heading1_prefix = 5,
  sym_heading2_prefix = 6,
  sym_heading3_prefix = 7,
  sym_heading4_prefix = 8,
  sym_heading5_prefix = 9,
  sym_heading6_prefix = 10,
  sym_quote = 11,
  sym_unordered_list = 12,
  sym_paragraph_delimiter = 13,
  sym_document = 14,
  sym_paragraph = 15,
  sym__heading = 16,
  sym_heading1 = 17,
  sym_heading2 = 18,
  sym_heading3 = 19,
  sym_heading4 = 20,
  sym_heading5 = 21,
  sym_heading6 = 22,
  aux_sym_document_repeat1 = 23,
  aux_sym_paragraph_repeat1 = 24,
  aux_sym_heading1_repeat1 = 25,
  aux_sym_heading2_repeat1 = 26,
  aux_sym_heading3_repeat1 = 27,
  aux_sym_heading4_repeat1 = 28,
  aux_sym_heading5_repeat1 = 29,
  aux_sym_heading6_repeat1 = 30,
  anon_alias_sym__segment = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__standalone_break] = "_standalone_break",
  [sym__] = "_",
  [sym_paragraph_segment] = "paragraph_segment",
  [sym__hard_line_break] = "_hard_line_break",
  [sym_heading1_prefix] = "heading1_prefix",
  [sym_heading2_prefix] = "heading2_prefix",
  [sym_heading3_prefix] = "heading3_prefix",
  [sym_heading4_prefix] = "heading4_prefix",
  [sym_heading5_prefix] = "heading5_prefix",
  [sym_heading6_prefix] = "heading6_prefix",
  [sym_quote] = "quote",
  [sym_unordered_list] = "unordered_list",
  [sym_paragraph_delimiter] = "paragraph_delimiter",
  [sym_document] = "document",
  [sym_paragraph] = "paragraph",
  [sym__heading] = "_heading",
  [sym_heading1] = "heading1",
  [sym_heading2] = "heading2",
  [sym_heading3] = "heading3",
  [sym_heading4] = "heading4",
  [sym_heading5] = "heading5",
  [sym_heading6] = "heading6",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_heading1_repeat1] = "heading1_repeat1",
  [aux_sym_heading2_repeat1] = "heading2_repeat1",
  [aux_sym_heading3_repeat1] = "heading3_repeat1",
  [aux_sym_heading4_repeat1] = "heading4_repeat1",
  [aux_sym_heading5_repeat1] = "heading5_repeat1",
  [aux_sym_heading6_repeat1] = "heading6_repeat1",
  [anon_alias_sym__segment] = "_segment",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__standalone_break] = sym__standalone_break,
  [sym__] = sym__,
  [sym_paragraph_segment] = sym_paragraph_segment,
  [sym__hard_line_break] = sym__hard_line_break,
  [sym_heading1_prefix] = sym_heading1_prefix,
  [sym_heading2_prefix] = sym_heading2_prefix,
  [sym_heading3_prefix] = sym_heading3_prefix,
  [sym_heading4_prefix] = sym_heading4_prefix,
  [sym_heading5_prefix] = sym_heading5_prefix,
  [sym_heading6_prefix] = sym_heading6_prefix,
  [sym_quote] = sym_quote,
  [sym_unordered_list] = sym_unordered_list,
  [sym_paragraph_delimiter] = sym_paragraph_delimiter,
  [sym_document] = sym_document,
  [sym_paragraph] = sym_paragraph,
  [sym__heading] = sym__heading,
  [sym_heading1] = sym_heading1,
  [sym_heading2] = sym_heading2,
  [sym_heading3] = sym_heading3,
  [sym_heading4] = sym_heading4,
  [sym_heading5] = sym_heading5,
  [sym_heading6] = sym_heading6,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_heading1_repeat1] = aux_sym_heading1_repeat1,
  [aux_sym_heading2_repeat1] = aux_sym_heading2_repeat1,
  [aux_sym_heading3_repeat1] = aux_sym_heading3_repeat1,
  [aux_sym_heading4_repeat1] = aux_sym_heading4_repeat1,
  [aux_sym_heading5_repeat1] = aux_sym_heading5_repeat1,
  [aux_sym_heading6_repeat1] = aux_sym_heading6_repeat1,
  [anon_alias_sym__segment] = anon_alias_sym__segment,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__standalone_break] = {
    .visible = false,
    .named = true,
  },
  [sym__] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph_segment] = {
    .visible = true,
    .named = true,
  },
  [sym__hard_line_break] = {
    .visible = false,
    .named = true,
  },
  [sym_heading1_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading2_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading3_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading4_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading5_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_heading6_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_unordered_list] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__heading] = {
    .visible = false,
    .named = true,
  },
  [sym_heading1] = {
    .visible = true,
    .named = true,
  },
  [sym_heading2] = {
    .visible = true,
    .named = true,
  },
  [sym_heading3] = {
    .visible = true,
    .named = true,
  },
  [sym_heading4] = {
    .visible = true,
    .named = true,
  },
  [sym_heading5] = {
    .visible = true,
    .named = true,
  },
  [sym_heading6] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading1_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading2_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading3_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading4_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading5_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading6_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym__segment] = {
    .visible = true,
    .named = false,
  },
};

enum {
  field_content = 1,
  field_title = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_title] = "title",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_title, 1},
  [1] =
    {field_content, 2},
    {field_title, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym__segment,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym__standalone_break);
      if (lookahead == '\n') ADVANCE(2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 0, .external_lex_state = 3},
  [18] = {.lex_state = 0, .external_lex_state = 3},
  [19] = {.lex_state = 0, .external_lex_state = 3},
  [20] = {.lex_state = 0, .external_lex_state = 3},
  [21] = {.lex_state = 0, .external_lex_state = 3},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 4},
  [32] = {.lex_state = 0, .external_lex_state = 4},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 4},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0, .external_lex_state = 4},
  [38] = {.lex_state = 0, .external_lex_state = 4},
};

enum {
  ts_external_token__ = 0,
  ts_external_token_paragraph_segment = 1,
  ts_external_token__hard_line_break = 2,
  ts_external_token_heading1_prefix = 3,
  ts_external_token_heading2_prefix = 4,
  ts_external_token_heading3_prefix = 5,
  ts_external_token_heading4_prefix = 6,
  ts_external_token_heading5_prefix = 7,
  ts_external_token_heading6_prefix = 8,
  ts_external_token_quote = 9,
  ts_external_token_unordered_list = 10,
  ts_external_token_paragraph_delimiter = 11,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__] = sym__,
  [ts_external_token_paragraph_segment] = sym_paragraph_segment,
  [ts_external_token__hard_line_break] = sym__hard_line_break,
  [ts_external_token_heading1_prefix] = sym_heading1_prefix,
  [ts_external_token_heading2_prefix] = sym_heading2_prefix,
  [ts_external_token_heading3_prefix] = sym_heading3_prefix,
  [ts_external_token_heading4_prefix] = sym_heading4_prefix,
  [ts_external_token_heading5_prefix] = sym_heading5_prefix,
  [ts_external_token_heading6_prefix] = sym_heading6_prefix,
  [ts_external_token_quote] = sym_quote,
  [ts_external_token_unordered_list] = sym_unordered_list,
  [ts_external_token_paragraph_delimiter] = sym_paragraph_delimiter,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__] = true,
    [ts_external_token_paragraph_segment] = true,
    [ts_external_token__hard_line_break] = true,
    [ts_external_token_heading1_prefix] = true,
    [ts_external_token_heading2_prefix] = true,
    [ts_external_token_heading3_prefix] = true,
    [ts_external_token_heading4_prefix] = true,
    [ts_external_token_heading5_prefix] = true,
    [ts_external_token_heading6_prefix] = true,
    [ts_external_token_quote] = true,
    [ts_external_token_unordered_list] = true,
    [ts_external_token_paragraph_delimiter] = true,
  },
  [2] = {
    [ts_external_token_paragraph_segment] = true,
    [ts_external_token_heading1_prefix] = true,
    [ts_external_token_heading2_prefix] = true,
    [ts_external_token_heading3_prefix] = true,
    [ts_external_token_heading4_prefix] = true,
    [ts_external_token_heading5_prefix] = true,
    [ts_external_token_heading6_prefix] = true,
    [ts_external_token_quote] = true,
    [ts_external_token_unordered_list] = true,
    [ts_external_token_paragraph_delimiter] = true,
  },
  [3] = {
    [ts_external_token_paragraph_segment] = true,
    [ts_external_token__hard_line_break] = true,
    [ts_external_token_heading1_prefix] = true,
    [ts_external_token_heading2_prefix] = true,
    [ts_external_token_heading3_prefix] = true,
    [ts_external_token_heading4_prefix] = true,
    [ts_external_token_heading5_prefix] = true,
    [ts_external_token_heading6_prefix] = true,
    [ts_external_token_quote] = true,
    [ts_external_token_unordered_list] = true,
    [ts_external_token_paragraph_delimiter] = true,
  },
  [4] = {
    [ts_external_token_paragraph_segment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__standalone_break] = ACTIONS(1),
    [sym__] = ACTIONS(1),
    [sym_paragraph_segment] = ACTIONS(1),
    [sym__hard_line_break] = ACTIONS(1),
    [sym_heading1_prefix] = ACTIONS(1),
    [sym_heading2_prefix] = ACTIONS(1),
    [sym_heading3_prefix] = ACTIONS(1),
    [sym_heading4_prefix] = ACTIONS(1),
    [sym_heading5_prefix] = ACTIONS(1),
    [sym_heading6_prefix] = ACTIONS(1),
    [sym_quote] = ACTIONS(1),
    [sym_unordered_list] = ACTIONS(1),
    [sym_paragraph_delimiter] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(36),
    [sym_paragraph] = STATE(3),
    [sym__heading] = STATE(3),
    [sym_heading1] = STATE(3),
    [sym_heading2] = STATE(3),
    [sym_heading3] = STATE(3),
    [sym_heading4] = STATE(3),
    [sym_heading5] = STATE(3),
    [sym_heading6] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(28),
    [sym__standalone_break] = ACTIONS(3),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_heading1_prefix] = ACTIONS(7),
    [sym_heading2_prefix] = ACTIONS(9),
    [sym_heading3_prefix] = ACTIONS(11),
    [sym_heading4_prefix] = ACTIONS(13),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(17),
    [sym_quote] = ACTIONS(3),
    [sym_unordered_list] = ACTIONS(3),
    [sym_paragraph_delimiter] = ACTIONS(3),
  },
  [2] = {
    [sym_paragraph] = STATE(2),
    [sym__heading] = STATE(2),
    [sym_heading1] = STATE(2),
    [sym_heading2] = STATE(2),
    [sym_heading3] = STATE(2),
    [sym_heading4] = STATE(2),
    [sym_heading5] = STATE(2),
    [sym_heading6] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym__standalone_break] = ACTIONS(21),
    [sym_paragraph_segment] = ACTIONS(24),
    [sym_heading1_prefix] = ACTIONS(27),
    [sym_heading2_prefix] = ACTIONS(30),
    [sym_heading3_prefix] = ACTIONS(33),
    [sym_heading4_prefix] = ACTIONS(36),
    [sym_heading5_prefix] = ACTIONS(39),
    [sym_heading6_prefix] = ACTIONS(42),
    [sym_quote] = ACTIONS(21),
    [sym_unordered_list] = ACTIONS(21),
    [sym_paragraph_delimiter] = ACTIONS(21),
  },
  [3] = {
    [sym_paragraph] = STATE(2),
    [sym__heading] = STATE(2),
    [sym_heading1] = STATE(2),
    [sym_heading2] = STATE(2),
    [sym_heading3] = STATE(2),
    [sym_heading4] = STATE(2),
    [sym_heading5] = STATE(2),
    [sym_heading6] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym__standalone_break] = ACTIONS(47),
    [sym_paragraph_segment] = ACTIONS(5),
    [sym_heading1_prefix] = ACTIONS(7),
    [sym_heading2_prefix] = ACTIONS(9),
    [sym_heading3_prefix] = ACTIONS(11),
    [sym_heading4_prefix] = ACTIONS(13),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(17),
    [sym_quote] = ACTIONS(47),
    [sym_unordered_list] = ACTIONS(47),
    [sym_paragraph_delimiter] = ACTIONS(47),
  },
  [4] = {
    [sym_paragraph] = STATE(6),
    [sym_heading2] = STATE(6),
    [sym_heading3] = STATE(6),
    [sym_heading4] = STATE(6),
    [sym_heading5] = STATE(6),
    [sym_heading6] = STATE(6),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading1_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym__standalone_break] = ACTIONS(51),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(51),
    [sym_heading1_prefix] = ACTIONS(49),
    [sym_heading2_prefix] = ACTIONS(9),
    [sym_heading3_prefix] = ACTIONS(11),
    [sym_heading4_prefix] = ACTIONS(13),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(49),
    [sym_unordered_list] = ACTIONS(49),
    [sym_paragraph_delimiter] = ACTIONS(49),
  },
  [5] = {
    [sym_paragraph] = STATE(5),
    [sym_heading2] = STATE(5),
    [sym_heading3] = STATE(5),
    [sym_heading4] = STATE(5),
    [sym_heading5] = STATE(5),
    [sym_heading6] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading1_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym__standalone_break] = ACTIONS(59),
    [sym_paragraph_segment] = ACTIONS(62),
    [sym__hard_line_break] = ACTIONS(59),
    [sym_heading1_prefix] = ACTIONS(57),
    [sym_heading2_prefix] = ACTIONS(65),
    [sym_heading3_prefix] = ACTIONS(68),
    [sym_heading4_prefix] = ACTIONS(71),
    [sym_heading5_prefix] = ACTIONS(74),
    [sym_heading6_prefix] = ACTIONS(77),
    [sym_quote] = ACTIONS(57),
    [sym_unordered_list] = ACTIONS(57),
    [sym_paragraph_delimiter] = ACTIONS(57),
  },
  [6] = {
    [sym_paragraph] = STATE(5),
    [sym_heading2] = STATE(5),
    [sym_heading3] = STATE(5),
    [sym_heading4] = STATE(5),
    [sym_heading5] = STATE(5),
    [sym_heading6] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading1_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(80),
    [sym__standalone_break] = ACTIONS(82),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(82),
    [sym_heading1_prefix] = ACTIONS(80),
    [sym_heading2_prefix] = ACTIONS(9),
    [sym_heading3_prefix] = ACTIONS(11),
    [sym_heading4_prefix] = ACTIONS(13),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(80),
    [sym_unordered_list] = ACTIONS(80),
    [sym_paragraph_delimiter] = ACTIONS(80),
  },
  [7] = {
    [sym_paragraph] = STATE(7),
    [sym_heading3] = STATE(7),
    [sym_heading4] = STATE(7),
    [sym_heading5] = STATE(7),
    [sym_heading6] = STATE(7),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading2_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(84),
    [sym__standalone_break] = ACTIONS(86),
    [sym_paragraph_segment] = ACTIONS(89),
    [sym__hard_line_break] = ACTIONS(86),
    [sym_heading1_prefix] = ACTIONS(84),
    [sym_heading2_prefix] = ACTIONS(84),
    [sym_heading3_prefix] = ACTIONS(92),
    [sym_heading4_prefix] = ACTIONS(95),
    [sym_heading5_prefix] = ACTIONS(98),
    [sym_heading6_prefix] = ACTIONS(101),
    [sym_quote] = ACTIONS(84),
    [sym_unordered_list] = ACTIONS(84),
    [sym_paragraph_delimiter] = ACTIONS(84),
  },
  [8] = {
    [sym_paragraph] = STATE(9),
    [sym_heading3] = STATE(9),
    [sym_heading4] = STATE(9),
    [sym_heading5] = STATE(9),
    [sym_heading6] = STATE(9),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading2_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(104),
    [sym__standalone_break] = ACTIONS(106),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(106),
    [sym_heading1_prefix] = ACTIONS(104),
    [sym_heading2_prefix] = ACTIONS(104),
    [sym_heading3_prefix] = ACTIONS(11),
    [sym_heading4_prefix] = ACTIONS(13),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(104),
    [sym_unordered_list] = ACTIONS(104),
    [sym_paragraph_delimiter] = ACTIONS(104),
  },
  [9] = {
    [sym_paragraph] = STATE(7),
    [sym_heading3] = STATE(7),
    [sym_heading4] = STATE(7),
    [sym_heading5] = STATE(7),
    [sym_heading6] = STATE(7),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading2_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(108),
    [sym__standalone_break] = ACTIONS(110),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(110),
    [sym_heading1_prefix] = ACTIONS(108),
    [sym_heading2_prefix] = ACTIONS(108),
    [sym_heading3_prefix] = ACTIONS(11),
    [sym_heading4_prefix] = ACTIONS(13),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(108),
    [sym_unordered_list] = ACTIONS(108),
    [sym_paragraph_delimiter] = ACTIONS(108),
  },
  [10] = {
    [sym_paragraph] = STATE(10),
    [sym_heading4] = STATE(10),
    [sym_heading5] = STATE(10),
    [sym_heading6] = STATE(10),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading3_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym__standalone_break] = ACTIONS(114),
    [sym_paragraph_segment] = ACTIONS(117),
    [sym__hard_line_break] = ACTIONS(114),
    [sym_heading1_prefix] = ACTIONS(112),
    [sym_heading2_prefix] = ACTIONS(112),
    [sym_heading3_prefix] = ACTIONS(112),
    [sym_heading4_prefix] = ACTIONS(120),
    [sym_heading5_prefix] = ACTIONS(123),
    [sym_heading6_prefix] = ACTIONS(126),
    [sym_quote] = ACTIONS(112),
    [sym_unordered_list] = ACTIONS(112),
    [sym_paragraph_delimiter] = ACTIONS(112),
  },
  [11] = {
    [sym_paragraph] = STATE(10),
    [sym_heading4] = STATE(10),
    [sym_heading5] = STATE(10),
    [sym_heading6] = STATE(10),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading3_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(129),
    [sym__standalone_break] = ACTIONS(131),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(131),
    [sym_heading1_prefix] = ACTIONS(129),
    [sym_heading2_prefix] = ACTIONS(129),
    [sym_heading3_prefix] = ACTIONS(129),
    [sym_heading4_prefix] = ACTIONS(13),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(129),
    [sym_unordered_list] = ACTIONS(129),
    [sym_paragraph_delimiter] = ACTIONS(129),
  },
  [12] = {
    [sym_paragraph] = STATE(11),
    [sym_heading4] = STATE(11),
    [sym_heading5] = STATE(11),
    [sym_heading6] = STATE(11),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading3_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(133),
    [sym__standalone_break] = ACTIONS(135),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(135),
    [sym_heading1_prefix] = ACTIONS(133),
    [sym_heading2_prefix] = ACTIONS(133),
    [sym_heading3_prefix] = ACTIONS(133),
    [sym_heading4_prefix] = ACTIONS(13),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(133),
    [sym_unordered_list] = ACTIONS(133),
    [sym_paragraph_delimiter] = ACTIONS(133),
  },
  [13] = {
    [sym_paragraph] = STATE(14),
    [sym_heading5] = STATE(14),
    [sym_heading6] = STATE(14),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading4_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(137),
    [sym__standalone_break] = ACTIONS(139),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(139),
    [sym_heading1_prefix] = ACTIONS(137),
    [sym_heading2_prefix] = ACTIONS(137),
    [sym_heading3_prefix] = ACTIONS(137),
    [sym_heading4_prefix] = ACTIONS(137),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(137),
    [sym_unordered_list] = ACTIONS(137),
    [sym_paragraph_delimiter] = ACTIONS(137),
  },
  [14] = {
    [sym_paragraph] = STATE(15),
    [sym_heading5] = STATE(15),
    [sym_heading6] = STATE(15),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading4_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(141),
    [sym__standalone_break] = ACTIONS(143),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(143),
    [sym_heading1_prefix] = ACTIONS(141),
    [sym_heading2_prefix] = ACTIONS(141),
    [sym_heading3_prefix] = ACTIONS(141),
    [sym_heading4_prefix] = ACTIONS(141),
    [sym_heading5_prefix] = ACTIONS(15),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(141),
    [sym_unordered_list] = ACTIONS(141),
    [sym_paragraph_delimiter] = ACTIONS(141),
  },
  [15] = {
    [sym_paragraph] = STATE(15),
    [sym_heading5] = STATE(15),
    [sym_heading6] = STATE(15),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading4_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(145),
    [sym__standalone_break] = ACTIONS(147),
    [sym_paragraph_segment] = ACTIONS(150),
    [sym__hard_line_break] = ACTIONS(147),
    [sym_heading1_prefix] = ACTIONS(145),
    [sym_heading2_prefix] = ACTIONS(145),
    [sym_heading3_prefix] = ACTIONS(145),
    [sym_heading4_prefix] = ACTIONS(145),
    [sym_heading5_prefix] = ACTIONS(153),
    [sym_heading6_prefix] = ACTIONS(156),
    [sym_quote] = ACTIONS(145),
    [sym_unordered_list] = ACTIONS(145),
    [sym_paragraph_delimiter] = ACTIONS(145),
  },
  [16] = {
    [sym_paragraph] = STATE(17),
    [sym_heading6] = STATE(17),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading5_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(159),
    [sym__standalone_break] = ACTIONS(161),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(161),
    [sym_heading1_prefix] = ACTIONS(159),
    [sym_heading2_prefix] = ACTIONS(159),
    [sym_heading3_prefix] = ACTIONS(159),
    [sym_heading4_prefix] = ACTIONS(159),
    [sym_heading5_prefix] = ACTIONS(159),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(159),
    [sym_unordered_list] = ACTIONS(159),
    [sym_paragraph_delimiter] = ACTIONS(159),
  },
  [17] = {
    [sym_paragraph] = STATE(18),
    [sym_heading6] = STATE(18),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading5_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(163),
    [sym__standalone_break] = ACTIONS(165),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(165),
    [sym_heading1_prefix] = ACTIONS(163),
    [sym_heading2_prefix] = ACTIONS(163),
    [sym_heading3_prefix] = ACTIONS(163),
    [sym_heading4_prefix] = ACTIONS(163),
    [sym_heading5_prefix] = ACTIONS(163),
    [sym_heading6_prefix] = ACTIONS(55),
    [sym_quote] = ACTIONS(163),
    [sym_unordered_list] = ACTIONS(163),
    [sym_paragraph_delimiter] = ACTIONS(163),
  },
  [18] = {
    [sym_paragraph] = STATE(18),
    [sym_heading6] = STATE(18),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading5_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(167),
    [sym__standalone_break] = ACTIONS(169),
    [sym_paragraph_segment] = ACTIONS(172),
    [sym__hard_line_break] = ACTIONS(169),
    [sym_heading1_prefix] = ACTIONS(167),
    [sym_heading2_prefix] = ACTIONS(167),
    [sym_heading3_prefix] = ACTIONS(167),
    [sym_heading4_prefix] = ACTIONS(167),
    [sym_heading5_prefix] = ACTIONS(167),
    [sym_heading6_prefix] = ACTIONS(175),
    [sym_quote] = ACTIONS(167),
    [sym_unordered_list] = ACTIONS(167),
    [sym_paragraph_delimiter] = ACTIONS(167),
  },
  [19] = {
    [sym_paragraph] = STATE(21),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading6_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(178),
    [sym__standalone_break] = ACTIONS(178),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(178),
    [sym_heading1_prefix] = ACTIONS(178),
    [sym_heading2_prefix] = ACTIONS(178),
    [sym_heading3_prefix] = ACTIONS(178),
    [sym_heading4_prefix] = ACTIONS(178),
    [sym_heading5_prefix] = ACTIONS(178),
    [sym_heading6_prefix] = ACTIONS(178),
    [sym_quote] = ACTIONS(178),
    [sym_unordered_list] = ACTIONS(178),
    [sym_paragraph_delimiter] = ACTIONS(178),
  },
  [20] = {
    [sym_paragraph] = STATE(20),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading6_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(180),
    [sym__standalone_break] = ACTIONS(180),
    [sym_paragraph_segment] = ACTIONS(182),
    [sym__hard_line_break] = ACTIONS(180),
    [sym_heading1_prefix] = ACTIONS(180),
    [sym_heading2_prefix] = ACTIONS(180),
    [sym_heading3_prefix] = ACTIONS(180),
    [sym_heading4_prefix] = ACTIONS(180),
    [sym_heading5_prefix] = ACTIONS(180),
    [sym_heading6_prefix] = ACTIONS(180),
    [sym_quote] = ACTIONS(180),
    [sym_unordered_list] = ACTIONS(180),
    [sym_paragraph_delimiter] = ACTIONS(180),
  },
  [21] = {
    [sym_paragraph] = STATE(20),
    [aux_sym_paragraph_repeat1] = STATE(26),
    [aux_sym_heading6_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(185),
    [sym__standalone_break] = ACTIONS(185),
    [sym_paragraph_segment] = ACTIONS(53),
    [sym__hard_line_break] = ACTIONS(185),
    [sym_heading1_prefix] = ACTIONS(185),
    [sym_heading2_prefix] = ACTIONS(185),
    [sym_heading3_prefix] = ACTIONS(185),
    [sym_heading4_prefix] = ACTIONS(185),
    [sym_heading5_prefix] = ACTIONS(185),
    [sym_heading6_prefix] = ACTIONS(185),
    [sym_quote] = ACTIONS(185),
    [sym_unordered_list] = ACTIONS(185),
    [sym_paragraph_delimiter] = ACTIONS(185),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      sym_paragraph_segment,
    STATE(28), 1,
      aux_sym_paragraph_repeat1,
    STATE(23), 2,
      sym_paragraph,
      aux_sym_heading6_repeat1,
    ACTIONS(178), 11,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote,
      sym_unordered_list,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [24] = 4,
    ACTIONS(5), 1,
      sym_paragraph_segment,
    STATE(28), 1,
      aux_sym_paragraph_repeat1,
    STATE(24), 2,
      sym_paragraph,
      aux_sym_heading6_repeat1,
    ACTIONS(185), 11,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote,
      sym_unordered_list,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [48] = 4,
    ACTIONS(187), 1,
      sym_paragraph_segment,
    STATE(28), 1,
      aux_sym_paragraph_repeat1,
    STATE(24), 2,
      sym_paragraph,
      aux_sym_heading6_repeat1,
    ACTIONS(180), 11,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote,
      sym_unordered_list,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [72] = 3,
    ACTIONS(192), 1,
      sym_paragraph_segment,
    STATE(25), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(190), 12,
      sym__hard_line_break,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote,
      sym_unordered_list,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [93] = 3,
    ACTIONS(53), 1,
      sym_paragraph_segment,
    STATE(25), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(195), 12,
      sym__hard_line_break,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote,
      sym_unordered_list,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [114] = 3,
    ACTIONS(197), 1,
      sym_paragraph_segment,
    STATE(27), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(190), 11,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote,
      sym_unordered_list,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [134] = 3,
    ACTIONS(5), 1,
      sym_paragraph_segment,
    STATE(27), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(195), 11,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote,
      sym_unordered_list,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [154] = 1,
    ACTIONS(200), 13,
      sym_paragraph_segment,
      sym__hard_line_break,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote,
      sym_unordered_list,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [170] = 1,
    ACTIONS(200), 12,
      sym_paragraph_segment,
      sym_heading1_prefix,
      sym_heading2_prefix,
      sym_heading3_prefix,
      sym_heading4_prefix,
      sym_heading5_prefix,
      sym_heading6_prefix,
      sym_quote,
      sym_unordered_list,
      sym_paragraph_delimiter,
      ts_builtin_sym_end,
      sym__standalone_break,
  [185] = 1,
    ACTIONS(202), 1,
      sym_paragraph_segment,
  [189] = 1,
    ACTIONS(204), 1,
      sym_paragraph_segment,
  [193] = 1,
    ACTIONS(206), 1,
      sym_paragraph_segment,
  [197] = 1,
    ACTIONS(208), 1,
      sym_paragraph_segment,
  [201] = 1,
    ACTIONS(210), 1,
      sym_paragraph_segment,
  [205] = 1,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
  [209] = 1,
    ACTIONS(214), 1,
      sym_paragraph_segment,
  [213] = 1,
    ACTIONS(216), 1,
      sym_paragraph_segment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(22)] = 0,
  [SMALL_STATE(23)] = 24,
  [SMALL_STATE(24)] = 48,
  [SMALL_STATE(25)] = 72,
  [SMALL_STATE(26)] = 93,
  [SMALL_STATE(27)] = 114,
  [SMALL_STATE(28)] = 134,
  [SMALL_STATE(29)] = 154,
  [SMALL_STATE(30)] = 170,
  [SMALL_STATE(31)] = 185,
  [SMALL_STATE(32)] = 189,
  [SMALL_STATE(33)] = 193,
  [SMALL_STATE(34)] = 197,
  [SMALL_STATE(35)] = 201,
  [SMALL_STATE(36)] = 205,
  [SMALL_STATE(37)] = 209,
  [SMALL_STATE(38)] = 213,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(30),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(33),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(32),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(31),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(35),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(37),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(34),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading1, 2, .production_id = 2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(5),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(29),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(32),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(31),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(35),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(37),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading1_repeat1, 2), SHIFT_REPEAT(38),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading1, 3, .production_id = 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(7),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(29),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(31),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(35),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(37),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading2_repeat1, 2), SHIFT_REPEAT(38),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading2, 2, .production_id = 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading2, 3, .production_id = 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(10),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(29),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(35),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(37),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading3_repeat1, 2), SHIFT_REPEAT(38),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading3, 3, .production_id = 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading3, 2, .production_id = 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading4, 2, .production_id = 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading4, 3, .production_id = 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(15),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(29),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(37),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading4_repeat1, 2), SHIFT_REPEAT(38),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading5, 2, .production_id = 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading5, 3, .production_id = 3),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2), SHIFT_REPEAT(18),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2), SHIFT_REPEAT(29),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading5_repeat1, 2), SHIFT_REPEAT(38),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading6, 2, .production_id = 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading6_repeat1, 2),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading6_repeat1, 2), SHIFT_REPEAT(29),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading6, 3, .production_id = 3),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading6_repeat1, 2), SHIFT_REPEAT(30),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(29),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(30),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 1, .production_id = 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [212] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_norg_external_scanner_create(void);
void tree_sitter_norg_external_scanner_destroy(void *);
bool tree_sitter_norg_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_norg_external_scanner_serialize(void *, char *);
void tree_sitter_norg_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_norg(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_norg_external_scanner_create,
      tree_sitter_norg_external_scanner_destroy,
      tree_sitter_norg_external_scanner_scan,
      tree_sitter_norg_external_scanner_serialize,
      tree_sitter_norg_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
